/**
 * Core vocabulary of the form engine.
 *
 * Everything downstream — the builder UI, the capture UI, request validation,
 * the REST API, CSV export and the analytics view generator — is driven by the
 * definitions in this package. Adding a field type must remain a single-file
 * change (see ./field-types/), so nothing here may hard-code a list of types.
 */

/** A translatable string, keyed by BCP-47 locale: `{ en: 'Name', hi: 'नाम' }`. */
export type I18nText = Record<string, string>;

/**
 * Field type identifiers.
 *
 * Deliberately a TypeScript union backed by a plain `text` column rather than a
 * Postgres enum: a new field type should not require a database migration on
 * top of its registry module.
 */
export type FieldDataType =
  | 'short_text'
  | 'long_text'
  | 'number'
  | 'integer'
  | 'date'
  | 'time'
  | 'datetime'
  | 'boolean'
  | 'single_choice'
  | 'multi_choice'
  | 'photo'
  | 'file'
  | 'geopoint'
  | 'phone'
  | 'signature'
  | 'rating'
  | 'repeat_group'
  | 'calculated'
  | 'subject_ref';

export type FormType = 'registration' | 'encounter' | 'standalone';

/** One selectable answer. `code` is the stable analytics identity; `label` is presentation. */
export interface OptionDefinition {
  code: string;
  label: I18nText;
  imageUrl?: string | null;
  sortOrder: number;
  isActive: boolean;
}

export interface OptionSetDefinition {
  id: string;
  code: string;
  name: I18nText;
  options: OptionDefinition[];
}

/**
 * A single question.
 *
 * `key` is immutable for the life of the form and is what the analytics column,
 * the API property and the CSV header are all named after. `label` is free to
 * change and be translated without any downstream consequence. Keeping these
 * two separate is what makes a user-editable schema survivable.
 */
export interface FieldDefinition {
  id: string;
  key: string;
  label: I18nText;
  help?: I18nText | null;
  dataType: FieldDataType;
  isRequired: boolean;
  /** No two records on this form may hold the same answer here. */
  isUnique: boolean;
  sortOrder: number;
  /** Set when this field lives inside a `repeat_group`. */
  parentGroupId?: string | null;
  /** Populated for `single_choice` / `multi_choice`. */
  optionSet?: OptionSetDefinition | null;
  /** Type-specific settings, validated by the field type's own `configSchema`. */
  config: Record<string, unknown>;
  /** When present, the field is only shown (and only validated) if this evaluates true. */
  visibilityRule?: RuleNode | null;
  isArchived: boolean;
  /**
   * Locales whose label or hint came from machine translation and have not been
   * checked by a person. Presentation only — the capture UI ignores these; the
   * builder uses them to flag drafts for review.
   */
  labelMachine?: Record<string, boolean> | null;
  helpMachine?: Record<string, boolean> | null;
  /**
   * Which purpose this question is collected for.
   *
   * Null while nobody has said. Carried on the definition rather than looked up
   * separately because the privacy notice is generated by grouping questions by
   * this, and the builder has to be able to show what is unattributed.
   */
  purposeId?: string | null;
  /** The answer described as data rather than as a question, for the notice. */
  dataDescription?: I18nText | null;
}

export interface FormVersionDefinition {
  id: string;
  formId: string;
  formSlug: string;
  versionNumber: number;
  name: I18nText;
  description?: I18nText | null;
  formType: FormType;
  subjectTypeId?: string | null;
  fields: FieldDefinition[];
}

// ---------------------------------------------------------------------------
// Visibility rules
// ---------------------------------------------------------------------------

/**
 * Skip logic, stored as a small JSON tree.
 *
 * The builder composes these from dropdowns ("Show only if [Pregnant?] is [Yes]")
 * and `evaluateRule` interprets them. It is a closed AST with no expression
 * parsing and no `eval`, so a form author can never inject executable code.
 */
export type RuleNode =
  | { op: 'and'; rules: RuleNode[] }
  | { op: 'or'; rules: RuleNode[] }
  | { op: 'not'; rule: RuleNode }
  | { op: ComparisonOp; field: string; value: RuleValue };

export type ComparisonOp =
  | 'eq'
  | 'neq'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'in'
  | 'not_in'
  | 'contains'
  | 'is_empty'
  | 'is_not_empty';

export type RuleValue = string | number | boolean | null | Array<string | number>;

/** A form's answers, keyed by field `key`. Repeat groups hold an array of sub-records. */
export type SubmissionData = Record<string, unknown>;
